In [1]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import os
import scipy.stats as si
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans

path = os.getcwd()
path = 'C:/Users/USER-PC/Documents/GitHub/homework/FE539'
S = 1500
rf = 0.0265
yields = pd.read_csv(path + '/yields.csv')
data = pd.read_csv(path + '/data.csv')
data = pd.read_csv(path + '/data.csv')
data = data[data['days'] < 501]
data = data[data['days'] > 10]
d1 = data[(data['type'] == 'C') & (data['strike'] < S)]
data = d1.append(data[(data['type'] == 'P') & (data['strike'] > S)])
data = data[data['strike'] > 1000]
data = data[data['strike'] < 2000]
callput = data['type'].values
T = (data['days']).values
K = (data['strike']).values
V = data['IV'].values
P = data['price'].values
len(data)

1329

In [60]:
def rbf_gaussian(x, c, beta):
    return np.exp(-beta*(np.linalg.norm(x-c)**2))

def rbf_multiquadratic(x, c, beta):
    return np.sqrt(np.linalg.norm(x-c)**2 + beta**2)

def rbf_thinplate(x, c, s):
    return ((np.linalg.norm(x-c))**2)*np.log(np.linalg.norm(x-c))

In [61]:
def kmeans(x, n):
    k_means = KMeans(n_clusters = n).fit(x)
    clusters = k_means.cluster_centers_
    labels = (k_means.labels_)
    distances = []
    for i in range(len(labels)):
        distances.append(np.linalg.norm(Xt[i] - clusters[labels[i]]))
    df = pd.DataFrame({'cluster':labels, 'distance':distances})
    stds = df.groupby(['cluster'])['distance'].std().values
    return clusters, stds



In [64]:
class RBFNet(object):
    def __init__(self, k = 5, lr = 0.01, epochs = 100, rbf = rbf_thinplate):
        self.k = k
        self.lr = lr
        self.epochs = epochs
        self.rbf = rbf
        
        self.w = np.array([np.random.randn(k), np.random.randn(k)]).T
        self.b = np.random.randn(1)
    def fit(self, X, y):
        self.centers = kmeans(X, self.k)[0]
        self.stds = kmeans(X, self.k)[1]
        
        for epoch in range(1):
            for i in range(X.shape[0]):
                a = np.array([self.rbf(X[i], c, s) for c, s in zip(self.centers, self.stds)])
                print(a)
                F = a.T.dot(self.w) + self.b
                print(F)
                break
rbfn = RBFNet()
y = V1
rbfn.fit(Xt, y)

[1380390.78073053 1997806.01582213 1159401.54506533  489910.19795462
  399578.61836989]
[   37521.94029607 -3963902.41734143]


In [48]:
Ta = np.array(T)
Ka = np.array(K)
Va = np.array(V)

idx = np.random.randint(len(T), size=1000)
K1 = Ka[idx]
T1 = Ta[idx]
V1 = Va[idx]
X = np.array([T1, K1, V1]).T
Xt = np.array([Ta, Ka]).T
n_clusters = 10
k_means = KMeans(n_clusters = n_clusters).fit(Xt)
clusters = k_means.cluster_centers_
labels = (k_means.labels_)
t = np.array([Xt, clusters[labels]])

print(clusters)
print(labels)
distances = []
for i in range(len(labels)):
    distances.append(np.linalg.norm(Xt[i] - clusters[labels[i]]))
df = pd.DataFrame({'cluster':labels, 'distance':distances})
df.groupby(['cluster'])['distance'].std().values

[[ 123.64705882 1798.52941176]
 [  49.71084337 1229.45783133]
 [ 481.66666667 1200.        ]
 [  57.08810573 1499.95594714]
 [  56.675      1079.475     ]
 [ 251.42682927 1387.68292683]
 [ 239.86363636 1140.68181818]
 [ 481.66666667 1590.38461538]
 [  51.40277778 1366.25      ]
 [ 229.37662338 1617.53246753]]
[7 7 7 ... 0 0 0]


array([45.42232658, 20.82723236, 53.12218643, 25.32780519, 20.74906253,
       24.88476818, 26.63107075, 85.02792412, 20.3829099 , 28.19478469])